In [1]:
import numpy as np

In [8]:
x= np.array([[1,2,3,4],[5,6,7,8]],np.int16)

In [9]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int16)

In [5]:
print(type(x))

<class 'numpy.ndarray'>


In [19]:
x[:,3]

array([4, 8], dtype=int16)

In [21]:
x[1,:]

array([5, 6, 7, 8], dtype=int16)

 numpy ndarray properties

In [22]:
x= np.array([[[1,2,3],[4,5,6]],[[0,-1,-2],[-3,-4,-5]]], np.int16)

In [23]:
x

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 0, -1, -2],
        [-3, -4, -5]]], dtype=int16)

In [28]:
x.shape #verify if it is three diamensional

(2, 2, 3)

In [27]:
x.ndim  #check dimension

3

In [29]:
x.dtype

dtype('int16')

In [30]:
x.size

12

In [31]:
x.nbytes

24

In [32]:
x.T

array([[[ 1,  0],
        [ 4, -3]],

       [[ 2, -1],
        [ 5, -4]],

       [[ 3, -2],
        [ 6, -5]]], dtype=int16)

numpy constants

In [33]:
np.inf

inf

In [34]:
np.NAN

nan

In [35]:
np.NINF

-inf

In [36]:
np.NZERO

-0.0

In [37]:
np.PZERO

0.0

In [38]:
np.e

2.718281828459045

In [40]:
np.pi

3.141592653589793

In [41]:
np.euler_gamma

0.5772156649015329

In [ ]:
np.