In [1]:
import numpy as np


In [8]:
x= np.empty([3,3],np.uint8)

In [3]:
x

array([[105, 108, 101],
       [115,  32,  40],
       [120,  56,  54]], dtype=int16)

In [9]:
x.ndim

2

In [10]:
y =  np.eye(3,dtype=np.uint8)

In [11]:
y

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=uint8)

In [26]:
y=np.eye(5,dtype=np.uint8,k=-1)
y

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=uint8)

In [31]:
x= np.identity(5, dtype = np.uint8)
x


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=uint8)

In [32]:
x=np.ones((2,5,5), dtype=np.int16)
x

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [33]:
x=np.zeros((2,5,5), dtype=np.int16)
x

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int16)

In [36]:
x=np.full((3,3,3), dtype=np.int16,fill_value=3)
x

array([[[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]],

       [[3, 3, 3],
        [3, 3, 3],
        [3, 3, 3]]], dtype=int16)

# Matrix creation routines

In [38]:
x = np.tri(3,3,k=0,dtype=np.uint16)
x

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]], dtype=uint16)

In [42]:
x = np.ones((5,5),dtype=np.uint16)
y = np.tril(x,k=-1)
y

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]], dtype=uint16)

In [46]:
x = np.ones((5,5),dtype=np.uint16)
y = np.triu(x,k=1)
y

array([[0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]], dtype=uint16)