In [1]:
import numpy as  np
x= np.arange(6)

In [2]:
x

array([0, 1, 2, 3, 4, 5])

In [4]:
y=x.reshape((3,2))

In [5]:
y


array([[0, 1],
       [2, 3],
       [4, 5]])

In [6]:
x = np.array([[0,1,2],[3,4,5]], dtype = np.int16)

In [7]:
x

array([[0, 1, 2],
       [3, 4, 5]], dtype=int16)

In [10]:
y= np.reshape(x,6)

In [15]:
y

array([0, 1, 2, 3, 4, 5], dtype=int16)

In [18]:
np.reshape(y,6)

array([0, 1, 2, 3, 4, 5], dtype=int16)

In [20]:
x.flatten()

array([0, 1, 2, 3, 4, 5], dtype=int16)

In [22]:
x.flatten('F')

array([0, 3, 1, 4, 2, 5], dtype=int16)

# Join array

In [27]:
x= np.array([1,2,3],  dtype = np.uint8)
y= np.array([4,5,6] , dtype = np.uint8)
z = np.array([7,8,9], dtype = np.uint8)

In [30]:
np.stack((x,y,z),axis=1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]], dtype=uint8)

In [31]:
np.vstack((x,y))

array([[1, 2, 3],
       [4, 5, 6]], dtype=uint8)

In [35]:
x= np.arange(9)
np.split(x,3)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

In [37]:
x=np.random.rand(4,4,4)

In [38]:
np.split(x,2)

[array([[[0.81111958, 0.9070171 , 0.13759782, 0.28068973],
         [0.44304077, 0.0994115 , 0.1303201 , 0.57479165],
         [0.28687635, 0.45033536, 0.59713653, 0.63695108],
         [0.45861254, 0.11102415, 0.29525204, 0.01054384]],
 
        [[0.35275231, 0.10547717, 0.35847652, 0.74471851],
         [0.58269753, 0.80359343, 0.26736658, 0.11547334],
         [0.57458797, 0.18465225, 0.77197701, 0.5877981 ],
         [0.77281767, 0.14326668, 0.56379987, 0.96358632]]]),
 array([[[0.27263433, 0.0619599 , 0.01542436, 0.82293659],
         [0.5553522 , 0.30709066, 0.16588386, 0.81585112],
         [0.12731277, 0.89154943, 0.84116686, 0.12918475],
         [0.12778194, 0.90219998, 0.39821085, 0.60601562]],
 
        [[0.22136377, 0.84205922, 0.21695376, 0.03144281],
         [0.08424007, 0.91753147, 0.86720428, 0.30315638],
         [0.63741942, 0.133016  , 0.42932046, 0.03065713],
         [0.91025324, 0.18184849, 0.82395267, 0.74793114]]])]

In [39]:
np.vsplit(x,2)

[array([[[0.81111958, 0.9070171 , 0.13759782, 0.28068973],
         [0.44304077, 0.0994115 , 0.1303201 , 0.57479165],
         [0.28687635, 0.45033536, 0.59713653, 0.63695108],
         [0.45861254, 0.11102415, 0.29525204, 0.01054384]],
 
        [[0.35275231, 0.10547717, 0.35847652, 0.74471851],
         [0.58269753, 0.80359343, 0.26736658, 0.11547334],
         [0.57458797, 0.18465225, 0.77197701, 0.5877981 ],
         [0.77281767, 0.14326668, 0.56379987, 0.96358632]]]),
 array([[[0.27263433, 0.0619599 , 0.01542436, 0.82293659],
         [0.5553522 , 0.30709066, 0.16588386, 0.81585112],
         [0.12731277, 0.89154943, 0.84116686, 0.12918475],
         [0.12778194, 0.90219998, 0.39821085, 0.60601562]],
 
        [[0.22136377, 0.84205922, 0.21695376, 0.03144281],
         [0.08424007, 0.91753147, 0.86720428, 0.30315638],
         [0.63741942, 0.133016  , 0.42932046, 0.03065713],
         [0.91025324, 0.18184849, 0.82395267, 0.74793114]]])]

In [40]:
x = np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [41]:
np.flip(x)

array([[15, 14, 13, 12],
       [11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [42]:
np.roll(x,8)

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7]])

In [43]:
np.rot90(x)

array([[ 3,  7, 11, 15],
       [ 2,  6, 10, 14],
       [ 1,  5,  9, 13],
       [ 0,  4,  8, 12]])