In [1]:
import numpy as np

In [3]:
r1= np.empty([3,3],np.int16)

In [4]:
r1


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int16)

In [7]:
r2 = np.eye(3,dtype=np.int16)

In [8]:
r2

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int16)

In [14]:
r3 = np.eye(5,dtype=np.int16,k=2)

In [15]:
r3

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int16)

In [18]:
r4 = np.identity(5,dtype=None)

In [19]:
r4

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
r5 = np.zeros((2,2,2),dtype=np.int16)

In [44]:
r5

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int16)

In [32]:
r6 = np.ones([2,5,5],dtype=np.int16)

In [33]:
r6

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

In [35]:
r7= np.full((3,3,3),dtype=np.int16,fill_value=7)

In [36]:
r7

array([[[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]],

       [[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]]], dtype=int16)

# Matix creation ruoutine

In [50]:
np.tri(3,3,k=0, dtype=np.int16)

array([[1, 0, 0],
       [1, 1, 0],
       [1, 1, 1]], dtype=int16)

In [54]:
np.tri(5,5,k=1, dtype=np.int16)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [57]:
np.tril((np.ones((5,5),dtype=np.int16)),k=-0)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0],
       [1, 1, 1, 1, 1]], dtype=int16)

In [62]:
np.triu((np.ones((5,5),dtype=np.int16)),k=-0)

array([[1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1],
       [0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1]], dtype=int16)